version: "3.8"

services:
  eureka:
    image: eureka
    container_name: eureka
    build: ./backend/eureka

    tty: true
    networks:
      - demo
    ports:
      - "1111:1111"

  proxy:
    image: proxy
    container_name: proxy
    build:
      context: ./backend/proxy
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:1111/eureka/
    tty: true
    networks:
      - demo
    ports:
      - "2222:2222"
    depends_on:
      - eureka

  Objavemicroservis:
    image: objavemicroservis
    container_name: objavemicroservis
    build:
      context: ./backend/Objavemicroservis
      dockerfile: Dockerfile
    tty: true
#    restart: on-failure
    networks:
      - demo
    ports:
      - "7876:7876"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:1111/eureka/
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: mysql
      DATABASE_SCHEMA: objavabaza?createDatabaseIfNotExist=true&serverTimezone=UTC
    depends_on:
      - eureka
      - mysql



  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  demo:
    name: demo
    driver: bridge