FROM maven:3.8.1-openjdk-16 AS appBuild
WORKDIR /usr/src/Objavemicroservis
COPY . .
RUN ["mvn", "package", "-DskipTests"]
FROM maven:3.8.1-openjdk-16 AS appBuild
WORKDIR /Objavemicroservis
COPY --from=appBuild /usr/src/Objavemicroservis/target/Objavemicroservis-0.0.1-SNAPSHOT.jar ./
EXPOSE 7876
CMD java -jar Objavemicroservis-0.0.1-SNAPSHOT.jar